<a href="https://colab.research.google.com/github/ArpitKadam/Attention-Is-All-You-Code/blob/main/Vector_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EMBEDDINGS**

In [ ]:
!pip install -Uq gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 33.9 MB/s eta 0:00:00


In [ ]:
import gensim.downloader as api

model =  api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
model['computer']

array([ 1.07421875e-01, -2.01171875e-01,  1.23046875e-01,  2.11914062e-01,
       -9.13085938e-02,  2.16796875e-01, -1.31835938e-01,  8.30078125e-02,
        2.02148438e-01,  4.78515625e-02,  3.66210938e-02, -2.45361328e-02,
        2.39257812e-02, -1.60156250e-01, -2.61230469e-02,  9.71679688e-02,
       -6.34765625e-02,  1.84570312e-01,  1.70898438e-01, -1.63085938e-01,
       -1.09375000e-01,  1.49414062e-01, -4.65393066e-04,  9.61914062e-02,
        1.68945312e-01,  2.60925293e-03,  8.93554688e-02,  6.49414062e-02,
        3.56445312e-02, -6.93359375e-02, -1.46484375e-01, -1.21093750e-01,
       -2.27539062e-01,  2.45361328e-02, -1.24511719e-01, -3.18359375e-01,
       -2.20703125e-01,  1.30859375e-01,  3.66210938e-02, -3.63769531e-02,
       -1.13281250e-01,  1.95312500e-01,  9.76562500e-02,  1.26953125e-01,
        6.59179688e-02,  6.93359375e-02,  1.02539062e-02,  1.75781250e-01,
       -1.68945312e-01,  1.21307373e-03, -2.98828125e-01, -1.15234375e-01,
        5.66406250e-02, -

In [ ]:
model['computer'].shape

(300,)

In [ ]:
model.most_similar(positive=['mouse', 'cpu'], negative=['motherboard'], topn=7)

[('cursor', 0.45342719554901123),
 ('rcb', 0.4400519132614136),
 ('microsoft', 0.4357083737850189),
 ('mac', 0.4268351197242737),
 ('mac_os_x', 0.4257684051990509),
 ('cursors', 0.42119190096855164),
 ('directx', 0.4159266948699951)]

In [ ]:
import numpy as np

word1 = "man"
word2 = "woman"

word3 = "semiconductor"
word4 = "earthworm"

word5 = "nigga"
word6 = "black"

vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]

magnitude1 = np.linalg.norm(vector_difference1)
magnitude2 = np.linalg.norm(vector_difference2)
magnitude3 = np.linalg.norm(vector_difference3)

print(f"The magnitude of the difference between {word1} and {word2} is {magnitude1:.2f}")
print(f"The magnitude of the difference between {word3} and {word4} is {magnitude2:.2f}")
print(f"The magnitude of the difference between {word5} and {word6} is {magnitude3:.2f}")

The magnitude of the difference between man and woman is 1.73
The magnitude of the difference between semiconductor and earthworm is 5.67
The magnitude of the difference between nigga and black is 3.83


In [ ]:
len(model.key_to_index)

3000000

In [ ]:
import torch

input_ids = torch.tensor([2, 3, 6, 7])

In [ ]:
vocab = model.key_to_index
reversed_vocab = {v: k for k, v in vocab.items()}
len(vocab)

3000000

In [ ]:
for i in input_ids:
  print(reversed_vocab[i.item()])

for
that
##
The


In [ ]:
vocab_size = 10
output_dim = 5

torch.manual_seed(100)

embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
print(len(embedding_layer.weight))
print(embedding_layer.weight)

10
Parameter containing:
tensor([[ 0.1268,  1.3564,  0.5632, -0.1039, -0.3575],
        [ 0.3917, -0.6801,  0.2409,  0.4698,  1.2426],
        [ 0.5403, -1.1454, -1.4592, -1.6281,  0.3834],
        [-0.1718, -3.1896,  1.5914, -0.0247, -0.8466],
        [ 0.0293, -0.5721, -1.2546,  0.0486,  1.1705],
        [-0.5410, -0.7116,  0.0575,  0.6263, -1.7736],
        [-0.2205,  2.7467, -1.7599,  1.0230,  0.8986],
        [ 0.8262, -0.3668, -0.4251, -1.2455,  1.1245],
        [ 1.3302,  0.0544, -0.6084, -1.3856,  1.0412],
        [-0.8043, -0.6244, -0.5882, -0.7553, -0.9577]], requires_grad=True)


In [ ]:
embedding_layer

In [ ]:
embedding_layer(input_ids)

# **POSITIONAL EMBEDDING**

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
import tiktoken

class GPTDataSetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.target_ids = []

    token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

    for i in range(0, len(token_ids) - max_length, stride):
      input_chunk = token_ids[i: i + max_length]
      target_chunk = token_ids[i+1: i + max_length + 1]

      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(target_chunk))

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, index):
    return self.input_ids[index], self.target_ids[index]


def create_dataloader_v1(txt, batch_size=4, max_length=128, stride=32, shuffle=True, drop_last=True, num_workers=0):

  tokenizer = tiktoken.get_encoding("gpt2")

  dataset = GPTDataSetV1(txt, tokenizer, max_length, stride)

  dataloader = DataLoader(
      dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers
  )

  return dataloader

In [ ]:
with open("/content/the-verdict.txt", "r", encoding="utf-8") as file:
    raw_text = file.read()

In [ ]:
max_length = 4

dataloader = create_dataloader_v1(raw_text, max_length=max_length,
                                  stride=max_length, shuffle=False,
                                  batch_size=8)

data_iter = iter(dataloader)

In [ ]:
input, targets = next(data_iter)

In [ ]:
print(input)
print(targets)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [ ]:
len(data_iter)

160

In [ ]:
vocab_size = 50257
ouput_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, ouput_dim)

In [ ]:
token_embeddings = token_embedding_layer(input)

In [ ]:
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [ ]:
contextual_length = max_length

positional_embedding_layer = torch.nn.Embedding(contextual_length, ouput_dim)

In [ ]:
positional_embedding = positional_embedding_layer(torch.arange(max_length))

In [ ]:
print(positional_embedding.shape)

torch.Size([4, 256])


In [ ]:
positional_embedding

tensor([[ 0.9672,  1.2683,  1.0630,  ...,  1.3986,  0.0512, -0.0214],
        [-0.4335,  0.0199, -0.1517,  ..., -0.5234, -0.1408,  0.3274],
        [-1.3747, -0.4409,  0.2756,  ..., -1.0390, -2.9409, -0.7339],
        [ 1.0577, -0.9666, -0.4904,  ...,  1.2635, -1.4978, -2.2226]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
input_embeddings = token_embeddings + positional_embedding

print(input_embeddings.shape)

torch.Size([8, 4, 256])
